set nocompatible               " be iMproved
filetype off                   " required!

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle
" required!
Plugin 'Gmarik/Vundle.vim'

" Personal Plugins
Plugin 'Altercation/Vim-Colors-Solarized'
Plugin 'Atweiden/Vim-Hudigraphs'
Plugin 'Bling/Vim-Airline'
Plugin 'ChrisKempson/Base16-vim'
Plugin 'FuzzyFinder'
Plugin 'Godlygeek/Tabular'
Plugin 'L9'
Plugin 'Lokaltog/Vim-Easymotion'
Plugin 'Potatoesmaster/i3-Vim-Syntax'
Plugin 'Rstacruz/Sparkup', {'rtp': 'vim/'}
Plugin 'Sickill/Vim-Monokai'
Plugin 'TPope/Vim-Dispatch'
Plugin 'TPope/Vim-Fugitive'
Plugin 'TPope/Vim-Repeat'
Plugin 'TPope/Vim-Surround'
Plugin 'Trusktr/Seti.vim'

" Syntax plugins
Plugin 'NGiNX.vim'

call vundle#end()
" End Plugins

filetype plugin indent on

" We like colors :D
set t_Co=256

" Powerline is awesome
set laststatus=2
" let g:Powerline_symbols = 'fancy'
let g:airline_powerline_fonts = 1

" Visual settings
hi clear
syntax on
set background=dark
colorscheme seti

" Couple settings
set number
set relativenumber
set cursorcolumn
set cursorline
set backupdir=/tmp
set swapfile
set dir=/tmp

" Remaps
nnoremap ; :
inoremap jj <Esc>
inoremap ;; <End>;<Esc>:w<CR>

let s:tabwidth=4
set shiftwidth=4
set softtabstop=4
set tabstop=4

" Searchoptions
set incsearch
set ignorecase
set hlsearch

let mapleader = ","
let g:mapleader = ","

" Down is really the next line
nnoremap j gj
nnoremap k gk

" Keybinds
vmap <leader>so :sort u<CR>

" Fast saves
nmap <leader><leader>w :w!<cr>
nmap <leader>p o<ESC>p

" I paste a lot from my X11 clipboard
nnoremap <leader>v "+p

" With a map leader it's possible to do extra key combinations
" Easymotion
nmap s <Plug>(easymotion-w)

" Fuzzyfinder keybindings
nmap <leader>f :FufFileWithCurrentBufferDir<CR>
nmap <leader>b :FufBuffer<CR>
nmap <leader>t :FufTaggedFile<CR>

" Git bindings
nnoremap <leader>ga :Git add %:p<CR><CR>
nnoremap <leader>gb :Gblame<CR>
nnoremap <leader>gs :Gstatus<CR>
nnoremap <leader>ge :Gedit<CR>
nnoremap <leader>gd :Gdiff<CR>
nnoremap <leader>gc :Gcommit -q<CR>
nnoremap <leader>gps :Dispatch! git push<CR>
nnoremap <leader>gpl :Dispatch! git pull<CR>
nnoremap <leader>go :Copen<CR>

" Quick alignment with Tabular
nmap <Leader>a= :Tabularize /=<CR>
vmap <Leader>a= :Tabularize /=<CR>
nmap <Leader>a: :Tabularize /:\zs<CR>
vmap <Leader>a: :Tabularize /:\zs<CR>

" Colourcolumn
highligh ColorColumn ctermbg=darkgrey
set colorcolumn=81,121

" Trailing whitespace and incorrect indentation
exec "set listchars=tab:\uBB\uBB,trail:\uB7,nbsp:~"
set list

" Since visual block mode is way better than visual mode; why don't we just swap them.
nnoremap    v   <C-V>
nnoremap <C-V>     v

vnoremap    v   <C-V>
vnoremap <C-V>     v

" Add slash seperated text object
onoremap <silent> i/ :<C-U>normal! T/vt/<CR> " inside /
onoremap <silent> a/ :<C-U>normal! F/vf/<CR> " around /
xnoremap <silent> i/ :<C-U>normal! T/vt/<CR> " inside /
xnoremap <silent> a/ :<C-U>normal! F/vf/<CR> " around /

" Line highlighting
hi LineNr term=bold cterm=NONE ctermfg=DarkGrey ctermbg=NONE gui=NONE guifg=DarkGrey guibg=NONE

" Spellcheck for English, Basic English and Dutch
nmap ;s  :set invspell spelllang=en<CR>
nmap ;ss :set invspell spelllang=en-basic<CR>
nmap ;sd :set invspell spelllang=nl<CR>

" Write
cmap w!! w !sudo tee > /dev/null %

" Map CTRL-K to a list diagraph without losing context
inoremap <expr> <C-K> ShowDigraphs()

function! ShowDigraphs ()
    digraphs
    call getchar()
    return "\<C-K>"
endfunction

highlight NonText ctermbg=none
