set nocompatible               " be iMproved
filetype off                   " required!

set rtp+=~/.vim/bundle/vundle
call vundle#rc()

" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'

" Personal bundles
Bundle 'tpope/vim-fugitive'
Bundle 'tpope/vim-repeat'
Bundle 'Lokaltog/vim-easymotion'
Bundle 'rstacruz/sparkup', {'rtp': 'vim/'}
Bundle 'L9'
Bundle 'FuzzyFinder'
Bundle 'svermeulen/vim-easyclip'
Bundle 'Lokaltog/vim-powerline'
Bundle 'Align'
Bundle 'tpope/vim-surround'
Bundle 'altercation/vim-colors-solarized'
Bundle 'chriskempson/base16-vim'

" End bundles
filetype plugin indent on

set t_Co=256

syntax on
set background=dark
colorscheme solarized

let s:tabwidth=4

let g:solarized_termtrans=1
let g:solarized_degrade=0
let g:solarized_bold=1
let g:solarized_italic=1
let g:solarized_underline=1
let g:solarized_visibility="normal"


hi clear
if exists("syntax_on")
	syntax reset
endif
let colors_name = "solarized"

syntax on
set background=dark
colorscheme solarized
