#!/bin/sh
# Check for whitespace errors before committing. Based upon the default
# pre-commit hook from git.

if git rev-parse --verify HEAD >/dev/null 2>&1; then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Print whitespace errors
exec git diff-index --check --cached $against --
