#!/bin/bash
vol=$(amixer get Master | grep 'Front Left:' | cut -d ' ' -f 7 | tr -d     '[\[\]]%')

echo "$vol%"

case $BLOCK_BUTTON in
	1) pavucontrol > /dev/null;;
	2) amixer -q sset Master toggle;;
	4) amixer -q sset Master 5%+ unmute;;
	5) amixer -q sset Master 5%- unmute;;
esac

if [ $vol -gt 100 ]; then
	exit 33
fi
