# Format variables
_fmt_reset="\e[0m"
_fmt_intense="\e[1m"
_fmt_normal="\e[2m"
_fmt_italic="\e[3m"
_fmt_underlined="\e[4m"
_fmt_blink="\e[5m"
_fmt_background="\e[7m"

_fmt_black="\[\e\[2;30m\]"
_fmt_red="\[\e\[2;31m\]"
_fmt_green="\[\e\[2;32m\]"
_fmt_brown="\[\e\[2;33m\]"
_fmt_dblue="\[\e\[2;34m\]"
_fmt_purple="\[\e\[2;35m\]"
_fmt_cyan="\[\e\[2;36m\]"
_fmt_lgrey="\[\e\[2;37m\]"

_fmt_grey="\[\e\[1;30m\]"
_fmt_lred="\[\e\[1;31m\]"
_fmt_lgreen="\[\e\[1;32m\]"
_fmt_lgreen="\e[0;32m"
_fmt_yellow="\[\e\[1;33m\]"
_fmt_blue="\[\e\[1;34m\]"
_fmt_lpurple="\[\e\[1;35m\]"
_fmt_lblue="\[\e\[1;36m\]"
_fmt_white="\[\e\[1;37m\]"

# Format variables
export _success_col="$_fmt_lgreen"
export _warning_col="\e[1;31m"
export _critical_col="\e[0;33m"
export _truncate_col="\e[0;33m"
export _normal_col="\e[0m"
