#!/usr/bin/python2
import glob
import os


def main():
    test = symlink()
    test.scan()
    test.parse()

    test.link()


class symlink:
    def __init__(self):
        self.files = []
        self.links = []

    def scan(self, clear=True):
        if clear:
            self.files = []

        # Find all the symlink files
        files = glob.glob('./*/.symlinks')

        # Loop through the symlink files and parse them
        for file in files:
            file = os.path.abspath(file)
            self.files.append(file)

        return self.files

    def parse(self):

        # Loop over the paths
        for path in self.files:

            # Get the absolute base path for the directory
            baseDir = os.path.split(path)[0] + '/'

            # Open the symlink file
            content = open(path, 'r').read()

            # Split the big blob of text into separate rule we can parse
            link = content.split('\n')[0:-1]

            # Loop through the rules and parse them
            for link in link:
                if link.find('=>'):
                    # Split the symlink into a file and destination
                    s = link.split('=>')

                    file = os.path.abspath(os.path.expanduser(os.path.join(baseDir, s[0].strip())))
                    dest = os.path.abspath(os.path.expanduser(s[1].strip()))

                    self.links.append((file, dest))

        return self.links

    def link(self):

        for link in self.links:

            file = link[0]
            dest = link[1]

            # Debug code
            print('Linking ' + file + ' to ' + dest)

            # If the destination doesn't exist yet, create the symlink
            if os.path.lexists(dest):
                print('File already exists')

            elif not os.path.exists(file):
                print("The file you're trying to link doesn't exist")

            else:
                # Finally create the symlink
                try:
                    os.symlink(file, dest)
                    print('Symlink created!')
                except OSError:
                    print("Symlink couldn't be created")

            print('--------------------')


# Call the middle function
if __name__ == "__main__":
    main()
