#!/bin/sh
export ENVIRONMENT="$HOME/Environment"
export PATH="$PATH:$ENVIRONMENT/bin"

# The XDG Path variables
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_DATA_DIRS="/usr/local/share/:/usr/share/"

if [ -f ${XDG_CONFIG_HOME:-~/.config}/user-dirs.dirs ]; then
    . ${XDG_CONFIG_HOME:-~/.config}/user-dirs.dirs
    export XDG_DESKTOP_DIR XDG_DOWNLOAD_DIR XDG_TEMPLATES_DIR XDG_PUBLICSHARE_DIR XDG_DOCUMENTS_DIR XDG_MUSIC_DIR XDG_PICTURES_DIR XDG_VIDEOS_DIR
fi

feh --bg-scale ~/Environment/wallpapers/arch2.png

[[ -f ~/.Xresources ]] && xrdb -merge "${HOME}/.Xresources"

# Start the SSH-agent
eval $(ssh-agent)

# Start the gnome keyring
eval $(/usr/bin/gnome-keyring-daemon --replace --components=gpg,pkcs11,secrets,ssh)
export SSH_ASKPASS SSH_AUTH_SOCK GPG_AGENT_INFO GNOME_KEYRING_CONTROL GNOME_KEYRING_PID

# Swapcaps
/usr/bin/setxkbmap -option 'ctrl:swapcaps'

# I sure do like some compositing
/usr/bin/xcompmgr -n &
