# Path to your oh-my-zsh configuration.
ENVIRONMENT=$HOME/Environment
ZSH=$ENVIRONMENT/zsh

cd $ENVIRONMENT
if [ -z "`git status -uno | sed -n 2p | grep up-to-date`" ]; then
	echo "There is an update in your environment"
	echo "Lemme pull that shit"
	git pull -ff > /dev/null
else
	echo "There are no updates for your environment"
fi

cd ~

[ -r "$ZSH/settings.zsh" ] && source "$ZSH/settings.zsh"

for file in $ZSH/conf/*.zsh; do
	[ -r "$file" ] && source "$file"
done
unset file

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

[ -s $HOME/.nvm/nvm.sh ] && . $HOME/.nvm/nvm.sh # This loads NVM
