# Enable terminal 256 colour support
export TERM=xterm-256color
[ -n "$TMUX" ] && export TERM=screen-256color

export ENVIRONMENT=$HOME/Environment
ZSH=$ENVIRONMENT/zsh
cdir=$ENVIRONMENT/.cdir

export PATH="$PATH:$ENVIRONMENT/bin:$HOME/.composer/vendor/bin:./vendor/bin"
export OS=$(lsb_release -si)

export USERRUNDIR="/run/user/$(id -u)"

function shell_log {
	if [[ "$USER" != 'root' ]] || [[ $DEBUG == true ]]; then
		echo $@
	fi
}

if [ -f $ENVIRONMENT/userspecific/zsh/before.zsh ]; then
    shell_log "Loading user settings (Before)"
    source $ENVIRONMENT/userspecific/zsh/before.zsh
fi

shell_log "Loading general settings"
[ -r "$ZSH/settings.zsh" ] && source "$ZSH/settings.zsh"

# Loading imported libraries
shell_log "Loading libraries"
for file in $ZSH/lib/*.zsh; do
    shell_log "Loading library: ($file)"
    [ -r "$file" ] && source "$file"
done

# Loading configs
shell_log "Loading configs"
for file in $ZSH/conf/*.zsh; do
    shell_log "Loading config: ($file)"
    [ -r "$file" ] && source "$file"
done
unset file

if [ -f $ENVIRONMENT/userspecific/zsh/after.zsh ]; then
    shell_log "Loading userspecific settings (after)"
    source $ENVIRONMENT/userspecific/zsh/after.zsh
fi

[ -f $cdir ] && shell_log "cdir found (`cat $cdir`)" && cd "`cat $cdir`" && rm "$cdir"

typeset -U path cdpath fpath

if [[ "$USER" != 'root' ]]; then
	clear

	if hash archey 2>/dev/null; then
		archey
	elif hash screenfetch 2>/dev/null; then
		screenfetch
	fi
fi
