# Path to your oh-my-zsh configuration.
ENVIRONMENT=$HOME/Environment
ZSH=$HOME/Environment/zsh

[ -r "$ZSH/settings.zsh" ] && source "$ZSH/settings.zsh"

for file in $ZSH/lib/*.zsh; do
	[ -r "$file" ] && source "$file"
done
unset file

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
